export const SET_PAINTINGS = "SET_PAINTINGS"
export const SET_CAROUSEL_PAINTINGS = "SET_CAROUSEL_PAINTINGS"
export const FILTERED_PAINTING_PAINTING_SIZE_CHECKED =
  "FILTERED_PAINTING_PAINTING_SIZE_CHECKED"
export const FILTERED_PAINTING_PAINTING_SUBJECT_CHECKED =
  "FILTERED_PAINTING_PAINTING_SUBJECT_CHECKED"
export const FILTERED_PAINTING_PAINTING_TYPE_CHECKED =
  "FILTERED_PAINTING_PAINTING_TYPE_CHECKED"
export const DRAWER_TOGGLED = "DRAWER_TOGGLED"
export const FILTERED_PAINTING_PAINTING_FORM_RESET =
  "FILTERED_PAINTING_PAINTING_FORM_RESET"
export const EDIT_PAINTING_SAVE_SUCCEEDED = "EDIT_PAINTING_SAVE_SUCCEEDED"
export const EDIT_PAINTING_UPDATED = "EDIT_PAINTING_UPDATED"
export const EDIT_PAINTING_LOADED = "EDIT_PAINTING_LOADED"
